name: Build and Run Java with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.GPT_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # or 11, depending on your Maven setup

      - name: Build with Maven
        run: mvn clean package

      - name: Run Java App
        run: java -cp target/classes com.yourpackage.Main